global:
  scrape_interval:     1s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'
 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['rhel8:9100']
      
rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
