global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'
 
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['rhel8:9100']
      
groups:
  - name: node_alerts
    rules:
    - alert: SelinuxDisabled
      expr: job:node_selinux_current_mode{job="node"} < 1
      for: 15s
      labels:
        severity: event_trigger
      annotations:
        summary: Security disabled

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
